#version: '3.8'

name: fuelphp-training

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fuelphp-app
    volumes:
      - ../:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: fuelphp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuelphp_db
      MYSQL_USER: fuelphp
      MYSQL_PASSWORD: 123456
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fuelphp-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_USER=fuelphp
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "8080:80"
    depends_on:
      - mysql
volumes:
  db_data:
